
require('keybinds')
require('plugins')
require('core/colorscheme')
require('core/main')
require('core/nvim-comment')
-- require('plugins/lsp/config')
-- require('plugins/lsp/nvim-cmp')
-- require('plugins/lsp/snippets')
-- require('plugins/lsp/css')
-- require('plugins/lsp/tsserver')
-- require('plugins/lsp/eslinter')
-- require('plugins/lualine')
require('plugins/lsp/mason')
require('plugins/notify')
require('plugins/nvim-tree')
require('plugins/formatter')
-- require('plugins/todo-comments')
-- -- require('plugins/typescript')
-- require('plugins/treesitter')
require('plugins/which-key')
