
require('keybinds')
require('core/main')
require('core/colorscheme')
require('core/nvim-comment')
require('plugins/lsp/config')
require('plugins/lsp/nvim-cmp')
require('plugins/lsp/snippets')
require('plugins/lsp/css')
require('plugins/lsp/tsserver')
require('plugins/lsp/eslinter')
require('plugins/lualine')
require('plugins/notify')
require('plugins/nvim-tree')
require('plugins/treesitter')
require('plugins/which-key')
